config/routes.rb
Rails.application.routes.draw do
  resources :locations
  devise_for :users

  root to: "locations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true

  geocoded_by :address
  after_validation :geocode
end

app/models/text_messager.rb
class TextMessager
  attr_reader :recipient, :message, :from

  def initialize(recipient:, message:, from: Rails.application.secrets.twilio_phone)
    @recipient = recipient
    @message = message
    @from = from
  end

  def send
    client = Twilio::REST::Client.new
    client.messages.create({
      from: from,
      to: recipient,
      body: message,
    })
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :authenticate_user!
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  before_action :set_location, only: [:show, :edit, :update, :destroy]

  # GET /locations
  def index
    @locations = SearchesLocations.new(query: params[:q]).call
  end

  # GET /locations/1
  def show
  end

  # GET /locations/new
  def new
    @location = Location.new
  end

  # GET /locations/1/edit
  def edit
  end

  # POST /locations
  def create
    service = CreatesLocation.new(location_params.to_h)
    service.call
    @location = service.location

    if service.success?
      redirect_to @location, notice: 'Location was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /locations/1
  def update
    if @location.update(location_params)
      redirect_to @location, notice: 'Location was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /locations/1
  def destroy
    @location.destroy

    redirect_to locations_url, notice: 'Location was successfully destroyed.'
  end

  private

  def set_location
    @location = Location.find(params[:id])
  end

  def location_params
    params.require(:location).permit(:title, :description, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Chicago Public Art Tracker</a>
    </div>

    <form class="navbar-form navbar-left" role="search" action="/">
      <div class="form-group">
        <input type="text" name="q" class="form-control" placeholder="Find art near...">
      </div>
      <button type="submit" class="btn btn-default">Find a Landmark</button>
    </form>

    <ul class='nav navbar-nav navbar-right'>
      <% if current_user %>
        <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to 'Register', new_user_registration_path %></li>
        <li><%= link_to 'Login', new_user_session_path %></li>
      <% end %>       
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chicago Public Art Tracker</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>

    <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' />
    <!-- https://bootswatch.com/simplex/ -->
    <link rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootswatch/3.3.7/simplex/bootstrap.min.css' />
    <style href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js'></style>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <div class='container'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>
  </body>
</html>

app/views/locations/_form.html.erb
<div class='well bs-component'>
  <%= form_for(location, html: { class: 'form-horizontal' }) do |f| %>
    <% if location.errors.any? %>
    <fieldset>
        <div id="error_explanation">
          <h2><%= pluralize(location.errors.count, "error") %> prohibited this location from being saved:</h2>

          <ul>
          <% location.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class='form-group'>
        <%= f.label :title, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :title, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :address, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_field :address, class: 'form-control', required: true %>
        </div>
      </div>

      <div class='form-group'>
        <%= f.label :description, class: 'col-lg-2' %>
        <div class='col-lg-10'>
        <%= f.text_area :description, class: 'form-control', required: true %>
        </div>
      </div>

      <div class="actions">
        <%= f.submit %>
      </div>
    <fieldset>
  <% end %>
</div>

app/views/locations/_google_map.html.erb
<iframe
  width="100%"
  height="350"
  frameborder="0" style="border:0"
  src="https://www.google.com/maps/embed/v1/place?key=<%= Rails.application.secrets.google_api_key
      %>&q=<%= location.latitude.floor(5) %>,<%= location.longitude.floor(5) %>" allowfullscreen>
</iframe>

app/views/locations/edit.html.erb
<div class='page-header'>
  <h1>Editing Location</h1>
</div>

<%= render 'form', location: @location %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<div class='page-header'>
  <h1>Current Public Art</h1>
</div>

<table class='table table-striped table-hover'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Address</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @locations.each do |location| %>
      <tr>
        <td><%= link_to location.title, location %></td>
        <td><%= location.address %></td>
        <td><%= link_to 'Edit', edit_location_path(location) %> | 
            <%= link_to 'Destroy', location, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Location', new_location_path, class: 'btn btn-primary' %>

app/views/locations/new.html.erb
<div class='page-header'>
  <h1>Add a New Location</h1>
</div>

<%= render 'form', location: @location %>

<%= link_to 'Back', locations_path %>

app/views/locations/show.html.erb
<div class='page-header'>
  <h1><%= @location.title %></h1>
</div>

<div class='row'>
  <div class='col-lg-6'>
    <h4>Description</h4>
    <p><%= @location.description %></p>

    <h4>Address</h4>
    <p><%= @location.address %></p>
  </div>

  <div class='col-lg-6'>
  <%= render 'google_map', location: @location %>
  </div>
</div>

<div class='well'>
  <%= link_to 'Edit', edit_location_path(@location), class: 'btn btn-primary' %> |
  <%= link_to 'Back', locations_path %>
</div>